FROM node:18 as builder

WORKDIR /usr/src/app
COPY package*.json ./

RUN apt-get update && apt-get install -y build-essential gcc g++ make python3 python3-pip
RUN npm install
RUN npm rebuild bcrypt --build-from-source

FROM node:18-slim

WORKDIR /usr/src/app

# Install OpenSSL library
RUN apt-get update && apt-get install -y openssl libssl-dev

COPY --from=builder /usr/src/app/node_modules ./node_modules

COPY . .
