FROM node:18

WORKDIR /usr/src/app

COPY package*.json ./

RUN apt-get update && apt-get install -y build-essential gcc g++ make python3 python3-pip && \
  npm ci && \
  npm install --save-dev && \
  npm rebuild bcrypt --build-from-source && \
  apt-get remove -y build-essential gcc g++ make python && \
  apt-get autoremove -y

COPY . .

RUN npx prisma generate
RUN npm run build
