export enum DefaultAirport {
  LAX = 'LAX',
  SVO = 'SVO',
  JFK = 'JFK',
  DXB = 'DXB',
  PEK = 'PEK',
  LHR = 'LHR',
  HND = 'HND',
  HKG = 'HKG',
  ORD = 'ORD',
  CDG = 'CDG',
  AMS = 'AMS',
  FRA = 'FRA',
  DFW = 'DFW',
  CAN = 'CAN',
  SIN = 'SIN',
  ICN = 'ICN',
  DEN = 'DEN',
  BKK = 'BKK',
  DEL = 'DEL',
  CGK = 'CGK',
  MAD = 'MAD',
  MUC = 'MUC',
  MCO = 'MCO',
  LAS = 'LAS',
  BOM = 'BOM',
  SYD = 'SYD',
  MIA = 'MIA',
  SEA = 'SEA',
  ATL = 'ATL',
  YYZ = 'YYZ',
  MEX = 'MEX',
  YVR = 'YVR',
  BCN = 'BCN',
  MNL = 'MNL',
  IST = 'IST',
  DME = 'DME',
  VKO = 'VKO',
  LED = 'LED',
  AER = 'AER',
  KRR = 'KRR',
  SVX = 'SVX',
  KUF = 'KUF',
  UFA = 'UFA',
  KZN = 'KZN',
}

export const defaultAirports = [
  {
    code: DefaultAirport.LAX,
    name: 'Los Angeles International Airport',
    city: 'Los Angeles',
    country: 'United States',
  },
  {
    code: DefaultAirport.SVO,
    name: 'Sheremetyevo International Airport',
    city: 'Moscow',
    country: 'Russia',
  },
  {
    code: DefaultAirport.JFK,
    name: 'John F. Kennedy International Airport',
    city: 'New York',
    country: 'United States',
  },
  {
    code: DefaultAirport.DXB,
    name: 'Dubai International Airport',
    city: 'Dubai',
    country: 'United Arab Emirates',
  },
  {
    code: DefaultAirport.PEK,
    name: 'Beijing Capital International Airport',
    city: 'Beijing',
    country: 'China',
  },
  {
    code: DefaultAirport.LHR,
    name: 'London Heathrow Airport',
    city: 'London',
    country: 'United Kingdom',
  },
  {
    code: DefaultAirport.HND,
    name: 'Tokyo Haneda Airport',
    city: 'Tokyo',
    country: 'Japan',
  },
  {
    code: DefaultAirport.HKG,
    name: 'Hong Kong International Airport',
    city: 'Hong Kong',
    country: 'Hong Kong',
  },
  {
    code: DefaultAirport.ORD,
    name: "O'Hare International Airport",
    city: 'Chicago',
    country: 'United States',
  },
  {
    code: DefaultAirport.CDG,
    name: 'Charles de Gaulle Airport',
    city: 'Paris',
    country: 'France',
  },
  {
    code: DefaultAirport.AMS,
    name: 'Amsterdam Airport Schiphol',
    city: 'Amsterdam',
    country: 'Netherlands',
  },
  {
    code: DefaultAirport.FRA,
    name: 'Frankfurt Airport',
    city: 'Frankfurt',
    country: 'Germany',
  },
  {
    code: DefaultAirport.DFW,
    name: 'Dallas/Fort Worth International Airport',
    city: 'Dallas',
    country: 'United States',
  },
  {
    code: DefaultAirport.CAN,
    name: 'Guangzhou Baiyun International Airport',
    city: 'Guangzhou',
    country: 'China',
  },
  {
    code: DefaultAirport.SIN,
    name: 'Singapore Changi Airport',
    city: 'Singapore',
    country: 'Singapore',
  },
  {
    code: DefaultAirport.ICN,
    name: 'Incheon International Airport',
    city: 'Seoul',
    country: 'South Korea',
  },
  {
    code: DefaultAirport.DEN,
    name: 'Denver International Airport',
    city: 'Denver',
    country: 'United States',
  },
  {
    code: DefaultAirport.BKK,
    name: 'Suvarnabhumi Airport',
    city: 'Bangkok',
    country: 'Thailand',
  },
  {
    code: DefaultAirport.DEL,
    name: 'Indira Gandhi International Airport',
    city: 'Delhi',
    country: 'India',
  },
  {
    code: DefaultAirport.CGK,
    name: 'Soekarno–Hatta International Airport',
    city: 'Jakarta',
    country: 'Indonesia',
  },
  {
    code: DefaultAirport.MAD,
    name: 'Adolfo Suárez Madrid–Barajas Airport',
    city: 'Madrid',
    country: 'Spain',
  },
  {
    code: DefaultAirport.MUC,
    name: 'Munich Airport',
    city: 'Munich',
    country: 'Germany',
  },
  {
    code: DefaultAirport.MCO,
    name: 'Orlando International Airport',
    city: 'Orlando',
    country: 'United States',
  },
  {
    code: DefaultAirport.LAS,
    name: 'McCarran International Airport',
    city: 'Las Vegas',
    country: 'United States',
  },
  {
    code: DefaultAirport.BOM,
    name: 'Chhatrapati Shivaji Maharaj International Airport',
    city: 'Mumbai',
    country: 'India',
  },
  {
    code: DefaultAirport.SYD,
    name: 'Sydney Kingsford Smith Airport',
    city: 'Sydney',
    country: 'Australia',
  },
  {
    code: DefaultAirport.MIA,
    name: 'Miami International Airport',
    city: 'Miami',
    country: 'United States',
  },
  {
    code: DefaultAirport.SEA,
    name: 'Seattle–Tacoma International Airport',
    city: 'Seattle',
    country: 'United States',
  },
];
